export const USERMODE = "USERMODE";
export const ISSELLER = "ISSELLER";
export const SETFREELANCERID = "SETFREELANCERID";
export const SETROLE = "SETROLE"
export const SETFREELANCERDATA = "SETFREELANCERDATA"
export const SETCLIENTDATA = "SETCLIENTDATA"
